### ISSUE TITLE
ssdd 精度问题

### ISSUE THREAD

**Issue by SAR-Images-Understanding-Yang** [HsLOL/Rotation-RetinaNet-PyTorch#1]
博主你好，我在mmrotate上实验ssdd，发现map只能到80，而我看你的实验可以到84以上，想问一下你的实验和mmrotate里面的retina有什么区别吗

**Comment by HsLOL** [comment]
您好，二者采用的数据增强方法不太一样，而且超参数如：batch size，学习率等可能都不太一样，具体的可以看下两边的代码
