### ISSUE TITLE
make 文件问题

### ISSUE THREAD

**Issue by xiaxiangyu** [HsLOL/Rotation-RetinaNet-PyTorch#2]
博主你好，请问执行完make指令后，运行训练脚本仍然提示ModuleNotFoundError: No module named 'utils.rotation_overlaps.rbox_overlaps'该如何解决呢。

**Comment by HsLOL** [comment]
您好，如果make正确执行后应该是没有什么问题的，我这面测试过

**Comment by HsLOL** [comment]
您好，如果make正确执行后应该是没有什么问题的，我这面测试过
